# Generated by Django 2.0.1 on 2018-06-24 00:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_pur_beurre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_category',
            name='category',
            field=models.ForeignKey(on_delete=True, to='website_pur_beurre.Category'),
        ),
        migrations.AlterField(
            model_name='food_category',
            name='food',
            field=models.ForeignKey(on_delete=True, to='website_pur_beurre.Food'),
        ),
        migrations.AlterField(
            model_name='food_user',
            name='food',
            field=models.ForeignKey(on_delete=True, to='website_pur_beurre.Food'),
        ),
        migrations.AlterField(
            model_name='food_user',
            name='user',
            field=models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
