# Generated by Django 2.0.1 on 2018-06-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_pur_beurre', '0002_auto_20180624_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='food',
            name='nutri_score',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='food',
            name='place',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='food',
            name='web_link',
            field=models.CharField(max_length=300),
        ),
    ]
