# Generated by Django 2.0.1 on 2018-06-24 01:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website_pur_beurre', '0003_auto_20180624_0218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food_Category',
            new_name='FoodCategory',
        ),
        migrations.RenameModel(
            old_name='Food_User',
            new_name='FoodUser',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='type',
            new_name='type_category',
        ),
    ]
